name: AI Magazine
favicon: null
layout_spectrum: 0.74804
typography_spectrum: 0.35398
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#212226'
    - '#a7d3ee'
    - '#6a96c5'
    - '#bf142e'
  brandStrength: 0.7957668085582554
  lightness: 0.23982876213267446
  saturation: 0.6599304201081395
  rhythmicContrast: 0.7923145745880902
purpose: []
