name: AI Magazine
favicon: null
layout_spectrum: 0.74804
typography_spectrum: 0.39642
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#9fb4d3'
    - '#0b1727'
    - '#293f57'
    - '#56749a'
  brandStrength: 0.7957668085582554
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
